### ISSUE TITLE
4.0 does not build with VCP4

### ISSUE THREAD

**Issue by lkarsten** [varnish/libvmod-softpurge#5]
Working on 1872e86, preparing a 1.0.0+4.0 version for VCP4:

```
+ make
make  all-recursive
make[1]: Entering directory '/home/lkarsten/work/libvmod-softpurge'
Making all in src
make[2]: Entering directory '/home/lkarsten/work/libvmod-softpurge/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/opt/vcp4/include/varnish-plus -I../src/foreign   -g -O2 -MT vmod_softpurge.lo -MD -MP -MF .deps/vmod_softpurge.Tpo -c -o vmod_softpurge.lo vmod_softpurge.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/opt/vcp4/include/varnish-plus -I../src/foreign -g -O2 -MT vmod_softpurge.lo -MD -MP -MF .deps/vmod_softpurge.Tpo -c vmod_softpurge.c  -fPIC -DPIC -o .libs/vmod_softpurge.o
vmod_softpurge.c: In function 'vmod_softpurge':
vmod_softpurge.c:81:26: warning: passing argument 2 of 'EXP_Ttl' from incompatible pointer type
       (EXP_Ttl(ctx->req, o) - now),
                          ^
In file included from vmod_softpurge.c:4:0:
/opt/vcp4/include/varnish-plus/cache/cache.h:1042:8: note: expected 'const struct objcore *' but argument is of type 'struct object *'
 double EXP_Ttl(const struct req *, const struct objcore *);
        ^
vmod_softpurge.c:82:26: warning: passing argument 2 of 'EXP_Ttl' from incompatible pointer type
       (EXP_Ttl(ctx->req, o) + o->exp.grace - now), n);
                          ^
In file included from vmod_softpurge.c:4:0:
/opt/vcp4/include/varnish-plus/cache/cache.h:1042:8: note: expected 'const struct objcore *' but argument is of type 'struct object *'
 double EXP_Ttl(const struct req *, const struct objcore *);
        ^
vmod_softpurge.c:82:32: error: 'struct object' has no member named 'exp'
       (EXP_Ttl(ctx->req, o) + o->exp.grace - now), n);
                                ^
vmod_softpurge.c:85:8: error: 'struct object' has no member named 'exp'
   if (o->exp.ttl > (now - o->exp.t_origin))
        ^
vmod_softpurge.c:85:28: error: 'struct object' has no member named 'exp'
   if (o->exp.ttl > (now - o->exp.t_origin))
                            ^
vmod_softpurge.c:86:26: error: 'struct object' has no member named 'exp'
    EXP_Rearm(o, now, 0, o->exp.grace, o->exp.keep);
                          ^
vmod_softpurge.c:86:40: error: 'struct object' has no member named 'exp'
    EXP_Rearm(o, now, 0, o->exp.grace, o->exp.keep);
                                        ^
vmod_softpurge.c:86:14: warning: passing argument 1 of 'EXP_Rearm' from incompatible pointer type
    EXP_Rearm(o, now, 0, o->exp.grace, o->exp.keep);
              ^
In file included from vmod_softpurge.c:4:0:
/opt/vcp4/include/varnish-plus/cache/cache.h:1046:6: note: expected 'struct objcore *' but argument is of type 'struct object *'
 void EXP_Rearm(struct objcore *oc, double now, double ttl, double grace,
      ^
vmod_softpurge.c:89:26: warning: passing argument 2 of 'EXP_Ttl' from incompatible pointer type
       (EXP_Ttl(ctx->req, o) - now),
                          ^
In file included from vmod_softpurge.c:4:0:
/opt/vcp4/include/varnish-plus/cache/cache.h:1042:8: note: expected 'const struct objcore *' but argument is of type 'struct object *'
 double EXP_Ttl(const struct req *, const struct objcore *);
        ^
vmod_softpurge.c:90:26: warning: passing argument 2 of 'EXP_Ttl' from incompatible pointer type
       (EXP_Ttl(ctx->req, o) + o->exp.grace - now), n);
                          ^
In file included from vmod_softpurge.c:4:0:
/opt/vcp4/include/varnish-plus/cache/cache.h:1042:8: note: expected 'const struct objcore *' but argument is of type 'struct object *'
 double EXP_Ttl(const struct req *, const struct objcore *);
        ^
vmod_softpurge.c:90:32: error: 'struct object' has no member named 'exp'
       (EXP_Ttl(ctx->req, o) + o->exp.grace - now), n);
                                ^
Makefile:439: recipe for target 'vmod_softpurge.lo' failed
make[2]: *** [vmod_softpurge.lo] Error 1
make[2]: Leaving directory '/home/lkarsten/work/libvmod-softpurge/src'
Makefile:503: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lkarsten/work/libvmod-softpurge'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by daghf** [comment]
Any update here, @fgsch?

**Comment by fgsch** [comment]
Next on my list. 
Been working on getting the 4.0 and master branches updated last week before I dive into this one.
